name: Validate and sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate OAS
        uses: readmeio/rdme@7.1.1
        with:
          rdme: validate token-auth.yml

      - name: Publish OAS to production
        uses: readmeio/rdme@7.1.1
        with:
          rdme: openapi token-auth.yml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}
